### ISSUE TITLE
Initial tasklist

### ISSUE THREAD

**Issue by nsvrn** [PradyumnaKrishna/bitnode#1]
- [ ] Convert to a user prompt > bitnode init > Enter binary url or press enter to use default url "https://.." > select mode (r for regtest, m for mainnet, t for testnet) >  prune node N?(in MB)(press enter to skip i.e. full-node)

- [ ] Suggest default urls for the latest bitcoin-core (can only focus on linux os for now)

- [ ] Ability to run dockerfile in podman or docker using a command that utilizes the output dockerfile and bitcoin.conf file 

- [ ] Add ability to run prune node snapshot (will add more details re: url etc. later)

**Comment by nsvrn** [comment]
@PradyumnaKrishna : I was wondering if the output of this user input is always going to be a dockerfile and a bitcoin.conf file, may be it's better to create a web page instead of cli prompt, from the webpage just generate the dockerfile and bitcoin.conf simultaneously on a webpage editor... which then a person can simply download as files or just copy paste wherever they wish to run this. 

Let me know your thoughts, I think UX might be better this way and a user would never need to trust or install any additional software.

As an example, someone has created similar UX for creating a PHP environment, but instead of button to create - we can just do real-time by dividing the webpage into 2 panels, user input form on the left and editor that updates dockerfile and bitcoin.conf text on the right.
https://phpdocker.io/

And here is another example of a webpage that actually does the bitcoin.conf part, so very similar to this one but add dockerfile to actually download, verify and run the binaries along.

https://jlopp.github.io/bitcoin-core-config-generator/
source code: https://github.com/jlopp/bitcoin-core-config-generator

**Comment by PradyumnaKrishna** [comment]
Yeah, I guess its a good idea. We can do this, let me know if you have any particular frontend in mind or python framework.

**Comment by nsvrn** [comment]
That's awesome! nah no preference - use whatever framework you're familiar with or you want to try, keep it simple for now as we figure out all the necessary user input options to make it easy and clean, we will improve the UI post.

**Comment by PradyumnaKrishna** [comment]
I have started work on the web app, but I am confused between server side rendering of dockerfile or client side. Because this decision might affect the future development of this tool.

**Comment by nsvrn** [comment]
that's awesome, i think client side might be better if easy(you can also refer how jameson lopp's config generator is handling it(i assume client side js), we will just let user copy paste the text... so may be we don't even need to do any file downloads etc.

**Comment by PradyumnaKrishna** [comment]
Hey I continued my work and created a python web app because jameson lopp's config generator was a much complex project.

I have few question to continue the progress:
1. Regarding the podman option I am not sure if it will be achieved in a web app.
2. What do you mean by prune node, can you guide me?

**Comment by nsvrn** [comment]
1. So podman is similar to docker, all it does is takes same Dockerfile so it's just a similar command like docker, nothing to do really on our side other than giving some command instructions to run using the dockerfile and bitcoin.conf we generate.... (podman is useful in cases where you don't have ability to run as root, I believe docker forces you to be root).
But we just need to take user input -> generate dockerfile and bitcoin.conf -> give instructions/commands on how to run in docker run as well as podman run. For now it's ok to skip the podman part if you prefer and we can refine rest of the stuff first, i think this will be trivial... most of the refinement will be needed around user input options.

2. Prune node basically gets rid of full historical blockchain data based upon the size in MB you provide, for instance if you 200MB - then it will still start downloading history from start (2009/2010) but will keep deleting data after validating in chunks and then only keep full tx data of most recent history only to fit 200MB space, only downside is that if you have a wallet that was created much prior to that cut-off then it won't be able to scan it's utxo(older unspent transactions). But if you're setting up a new wallet, this is good option for users as it saves disk space. Other minor downside is that a prune node is unable to feed full historical blocks to it's peers specially which are trying to boot new nodes. Additionally, since even for prune the software still starts downloading data from genesis block and only prunes after validating(validations are often like checking hashes of tx and blocks), it still takes very long time to boot the node. So another solution for that is taking a "trusted" snapshot of prune data, you can still validate the hash of it's most recent block against some other node (this is not ideal but this is useful for someone who wants to boot a node asap with minimal disk space) (there will be future trustless improvements like assumeutxo in the protcol itself in this regard but they're not implemented yet)

Ref: https://bitcoin.stackexchange.com/questions/92769/bitcoin-full-node-how-to-run-a-pruned-node-explaining-pruning

Also, this might be useful: https://github.com/ns-xvrn/docs

**Comment by nsvrn** [comment]
Also to add, we should start with only basic settings for bitcoin.conf file not an exhaustive list like jameson lopp's(we can add a link to his later for advanced users), we will keep user input minimal and easy for each mode to get it up and running as quickly as possible.

Also, don't worry about prune mode too much for now, may be publish first version with regtest and we can refine user input first before adding other modes because then we will have something to look at and refine.

**Comment by nsvrn** [comment]
This might be useful: https://github.com/SatoshiPortal/dockers

**Comment by PradyumnaKrishna** [comment]
Hey, I have updated the web app. Have a look:

<img width="1364" alt="Screenshot 2023-01-27 at 22 03 12" src="https://user-images.githubusercontent.com/51270439/215142066-a553c1d1-da78-416e-93ed-5affe61d05b7.png">

<img width="1137" alt="Screenshot 2023-01-27 at 22 07 56" src="https://user-images.githubusercontent.com/51270439/215142443-0f71a183-a56b-4dca-b2fc-111c836d7d72.png">

**Comment by nsvrn** [comment]
oh wow, this looks nice! I'm going to try this out later today

**Comment by nsvrn** [comment]
Just tried it, looks good... i will work through some more user input things next week to see what else we can add.

A few very minor things:

- [x] Copy icon to copy text on Dockerfile and conf textarea
- [x] Need some basic minimal instructions somewhere on this page in order to run docker after doing the copy... may be as a comment on the top of Dockerfile for now
- [x] Add rpc options (enable/disable,  leave username password values blank - user can fill only on his machine/server)
```
# [rpc]
server=1
#rpcuser=
#rpcpassword=
```


Hosted here: https://bitnode.nostr.express/

**Comment by PradyumnaKrishna** [comment]
All tasks done.

**Comment by nsvrn** [comment]
all looks great, closing this issue now, will open new one for further changes/additions
